### ISSUE TITLE
modbus tcp connection interrups

### ISSUE THREAD

**Issue by micha1983** [morkai/h5.modbus#10]
hi,
i testet the h5.modbus module.
i started a read connection to a wago 750-841 plc.
nearly after 3min i get always a disconnected event triggered.

the interuption takes 200ms. the pings during this timeperiod are constantly nearly at 6ms.
has somebody also have seen thhis phanomen?

**Comment by morkai** [comment]
Do you send any data during that time?

**Comment by micha1983** [comment]
only once at startup one holding for testing.
could this be the problem, that i should constantly send something?

**Comment by morkai** [comment]
Yes. The device you are using might be disconnecting you, because nothing is being sent and you're connected, so it might assume that the connection is broken.

**Comment by micha1983** [comment]
thanks for the feedback. i will test this later. 
Great support!

**Comment by micha1983** [comment]
ok. i've tested it and i'm writing at the moment every 10sec a value.
but i still habe the problems of an disconnect event.

**Comment by morkai** [comment]
Show me some code and its results :)

**Comment by micha1983** [comment]
ok. after my last post i disabled the powersave mode of my PC. at the moment i'm having a active connection since 20minutes. every second i'm writing one value

**Comment by micha1983** [comment]
ok it was the energysaving mode of my PC. sorry.
