### ISSUE TITLE
h5.modbus with 16bit floating point

### ISSUE THREAD

**Issue by micha1983** [morkai/h5.modbus#11]
HI,

has somebody used h5.modbus with 16bit floating point values?
at the moment i'm not sure if it's working, i only see 32bit floating point.

is 16bit possible?

**Comment by morkai** [comment]
The read/write multiple holding register functions work with instances of Buffer, so it doesn't matter what is in them.
You need to read a Buffer and then read 16-bit float with some [stackoverflow magic](http://stackoverflow.com/questions/28688838/convert-a-number-into-a-16-bit-float-stored-as-bytes-and-back).
