### ISSUE TITLE
Example for slave

### ISSUE THREAD

**Issue by Yarisrespect** [morkai/h5.modbus#17]
How to send request to the client?

I have following code:
```
listener.on('client', function(client){
    // how to send request?
});

const slave = new modbus.Slave({
    listener: listener,
    transport: transport,
    requestHandler: handleRequest
});
```
I'll be very thankful!

**Comment by morkai** [comment]
Option `requestHandler` must be specified and be a `function(number unit, Request request, function(any) respond)`. For example:
```js
function handleRequest(unit, request, respond)
{
  if (isValidRequest(unit, request))
  {
    respond(new Buffer([1, 2, 3, 4]));
  }
  else
  {
    respond(ExceptionCode.IllegalDataAddress);
  }
}
```
`respond()` takes a single argument that can be one of:
  - `ExceptionCode` enum - will send an exception response
  - an instance of `Response` corresponding to the received `Request`
  - an instance of `Error` (more like an object with a `message` property) - will send the Slave Device Failure exception
  - an instance of `Buffer` - will try to create an instance of `Response` corresponding to the received `Request` by using the `Response.fromBuffer()` (for example, if the request is `ReadHoldingRegistersRequest`, then the `ReadHoldingRegistersResponse.fromBuffer()` will be called)
  - an object - will try to create an instance of `Response` corresponding to the received `Request` by using the `Response.fromOptions()`.

See [examples\slave.js](https://github.com/morkai/h5.modbus/blob/master/examples/slave.js) for a full example.

**Comment by Yarisrespect** [comment]
What about transactions if it is tcp/ip?

**Comment by morkai** [comment]
Use `TcpListener` and `IpTransport`.

**Comment by Yarisrespect** [comment]
That's clear I mean executing concurrent transactions.

**Comment by morkai** [comment]
The `respond()` callback is unique to each request. If you receive 10 requests, the `requestHandler` will be called 10 times, each with different `request` and `respond`.

**Comment by Yarisrespect** [comment]
Thank you a lot! And last one question.
Am I correct?
To send command to the client I should send it in the request handler by calling a respond function?

**Comment by morkai** [comment]
Yes, you must call `respond()` to send a response to a request.

**Comment by Yarisrespect** [comment]
So, is modbus.Slave for emulating modbus device?

**Comment by morkai** [comment]
Yes, modbus.Slave=server and modbus.Master=client.
