### ISSUE TITLE
TCP Connection to different than localhost

### ISSUE THREAD

**Issue by rwenergy** [morkai/h5.modbus#27]
TCPConnection.js

    this.socketOptions = Object.assign( {}, options.TcpConnection.socketOptions);
    //this.socketOptions = Object.assign({port: 502, host: 'localhost'}, options.socketOptions);

I had to add this in my branch to connect to any other host than localhost.
Is this a bug or feature?

**Comment by morkai** [comment]
You shouldn't change anything if you want to connect to a different host.
```js
const master = modbus.createMaster({
  connection: {
    type: 'tcp',
    socketOptions: {
      host: 'not-localhost.com',
      port: 502
    }
  }
});
```
