### ISSUE TITLE
Cheking ExceptionResponse

### ISSUE THREAD

**Issue by goranach** [morkai/h5.modbus#8]
Could you explain how chek the response for exception.
There are isException() in ExceptionResponse, but not this in ReadHoldingRegistersResponse.
I chek existing data.
Thank you.

**Comment by morkai** [comment]
There's `Message` -> `Response` -> `ReadHoldingRegistersResponse`/`ExceptionResponse`.

The `isException()` is defined in `Response` and always returns `false`. Then it's overridden in `ExceptionResponse` to return `true`.

**Comment by goranach** [comment]
Sorry, I did not notice.
New version is very stable and interesting to reflection.
